import type { Locale } from "@/content/site";

export type UiCopy = {
  home: string;
  startProject: string;
  exploreServices: string;
  turnkeyProcess: string;
  occasions: string;
  whoWeServe: string;
  startingPoints: string;
  relatedServices: string;
  relatedTitle: string;
  relatedText: string;
  howWorkComes: string;
  industriesTeams: string;
  cmsReady: string;
  cmsTitle: string;
  cmsText: string;
  fromIdea: string;
  insights: string;
  insightsTitle: string;
  insightsText: string;
  challenge: string;
  approach: string;
  outcome: string;
  openResource: string;
  resourceNote: string;
  services: string;
  servicesTitle: string;
  servicesText: string;
  explore: string;
  testimonials: string;
  testimonialsTitle: string;
  testimonialsText: string;
  gallery: string;
  galleryTitle: string;
  galleryText: string;
  viewGallery: string;
  resources: string;
  resourcesTitle: string;
  resourcesText: string;
  nextStep: string;
  caseStudies: string;
  brandTagline: string;
};

export const ui: Record<Locale, UiCopy> = {
  en: {
    home: "Home",
    startProject: "Start a Project",
    exploreServices: "Explore Services",
    turnkeyProcess: "Turnkey Process",
    occasions: "Occasions and Seasonal Programs",
    whoWeServe: "Who We Serve",
    startingPoints: "Flexible Starting Points",
    relatedServices: "Related services",
    relatedTitle: "Combine services around the shape of the project.",
    relatedText: "Every project can be scoped around audience, scale, branding, destinations, and timing.",
    howWorkComes: "How the Work Comes Together",
    industriesTeams: "Industries and Teams",
    cmsReady: "CMS ready",
    cmsTitle: "Future industry pages are ready in the content model.",
    cmsText: "The gaming page is published now. Additional industries are held for deeper content before publishing.",
    fromIdea: "From Idea to Doorstep",
    insights: "Insights",
    insightsTitle: "Useful thinking for better corporate gifting.",
    insightsText: "Starter SEO content covering gifting strategy, VIP appreciation, holiday planning, branded boxes, and fulfillment logistics.",
    challenge: "Challenge",
    approach: "Possible Approach",
    outcome: "Intended Outcome",
    openResource: "Open resource",
    resourceNote: "This structure is ready for future gated download behavior. It is currently ungated and has no newsletter signup.",
    services: "Services",
    servicesTitle: "Services that can work together as one project.",
    servicesText: "Our emphasis is corporate gifting, gifting ideas, custom branded gift boxes and gifts as well as concierge services, and fulfillment.",
    explore: "Explore",
    testimonials: "Testimonials",
    testimonialsTitle: "The meaning of current testimonials is preserved.",
    testimonialsText: "The wording has been refreshed to feel clearer, more polished, and more enterprise-ready.",
    gallery: "Gallery",
    galleryTitle: "Visual context for gifting, packaging, and fulfillment.",
    galleryText: "Legacy source images are used as placeholders until premium imagery is generated.",
    viewGallery: "View Gallery",
    resources: "Resources",
    resourcesTitle: "Better gifting starts with better planning.",
    resourcesText: "Three ungated resources are ready now, with a structure that can be converted into PDFs later.",
    nextStep: "Next step",
    caseStudies: "Case Studies",
    brandTagline: "Corporate gifting concierge",
  },
  es: {
    home: "Inicio",
    startProject: "Iniciar un proyecto",
    exploreServices: "Ver servicios",
    turnkeyProcess: "Proceso llave en mano",
    occasions: "Ocasiones y programas de temporada",
    whoWeServe: "A quién servimos",
    startingPoints: "Puntos de partida flexibles",
    relatedServices: "Servicios relacionados",
    relatedTitle: "Combine servicios según la forma del proyecto.",
    relatedText: "Regalos corporativos, cajas personalizadas, conserjería y fulfillment se pueden usar juntos o por separado.",
    howWorkComes: "Cómo se articula el trabajo",
    industriesTeams: "Sectores y equipos",
    cmsReady: "Listo para CMS",
    cmsTitle: "Las páginas de sectores futuras ya caben en el modelo de contenido.",
    cmsText: "El sitio puede sumar páginas de industria sin cambiar la estructura de información pública.",
    fromIdea: "De la idea a la puerta",
    insights: "Artículos",
    insightsTitle: "Ideas útiles para un mejor gifting corporativo.",
    insightsText: "Notas sobre programas VIP, campañas de temporada, cajas de marca y logística.",
    challenge: "Reto",
    approach: "Enfoque posible",
    outcome: "Resultado previsto",
    openResource: "Recurso abierto",
    resourceNote: "Esto es una guía de planificación, no una lista de precios. Cada proyecto se cotiza según el alcance.",
    services: "Servicios",
    servicesTitle: "Servicios que pueden formar un solo proyecto.",
    servicesText: "Use un servicio o combínelos en un programa de gifting totalmente gestionado.",
    explore: "Explorar",
    testimonials: "Testimonios",
    testimonialsTitle: "Se conserva el sentido de los testimonios actuales.",
    testimonialsText: "Notas de clientes sobre almacenamiento, fulfillment, coordinación y cuidado — reescritas con claridad.",
    gallery: "Galería",
    galleryTitle: "Contexto visual para regalos, empaque y fulfillment.",
    galleryText: "Las imágenes actuales son de referencia hasta contar con fotografía premium.",
    viewGallery: "Ver galería",
    resources: "Recursos",
    resourcesTitle: "Un mejor regalo empieza con una mejor planificación.",
    resourcesText: "Prepare audiencia, escala, destinos y plazos antes de la primera conversación.",
    nextStep: "Siguiente paso",
    caseStudies: "Casos",
    brandTagline: "Concierge de gifting corporativo",
  },
  fr: {
    home: "Accueil",
    startProject: "Démarrer un projet",
    exploreServices: "Voir les services",
    turnkeyProcess: "Processus clé en main",
    occasions: "Occasions et programmes saisonniers",
    whoWeServe: "À qui s’adresse MorePower2You",
    startingPoints: "Points de départ souples",
    relatedServices: "Services liés",
    relatedTitle: "Combinez les services selon la forme du projet.",
    relatedText: "Cadeaux d’entreprise, coffrets, conciergerie et fulfillment peuvent s’utiliser ensemble ou séparément.",
    howWorkComes: "Comment le travail s’assemble",
    industriesTeams: "Secteurs et équipes",
    cmsReady: "Prêt pour le CMS",
    cmsTitle: "De futures pages sectorielles sont déjà prévues dans le modèle.",
    cmsText: "Le site peut ajouter des pages industrie sans changer la structure publique.",
    fromIdea: "De l’idée jusqu’à la porte",
    insights: "Articles",
    insightsTitle: "Des idées utiles pour un meilleur gifting d’entreprise.",
    insightsText: "Notes sur les programmes VIP, les campagnes saisonnières, les coffrets et la logistique.",
    challenge: "Défi",
    approach: "Approche possible",
    outcome: "Résultat visé",
    openResource: "Ressource ouverte",
    resourceNote: "Ceci est un guide de planification, pas une grille tarifaire. Chaque projet est chiffré selon le périmètre.",
    services: "Services",
    servicesTitle: "Des services qui peuvent former un seul projet.",
    servicesText: "Utilisez un service ou combinez-les dans un programme entièrement géré.",
    explore: "Découvrir",
    testimonials: "Témoignages",
    testimonialsTitle: "Le sens des témoignages actuels est conservé.",
    testimonialsText: "Retours clients sur le stockage, le fulfillment, la coordination et le soin — réécrits pour plus de clarté.",
    gallery: "Galerie",
    galleryTitle: "Contexte visuel pour les cadeaux, l’emballage et le fulfillment.",
    galleryText: "Les images actuelles servent de référence en attendant une photographie premium.",
    viewGallery: "Voir la galerie",
    resources: "Ressources",
    resourcesTitle: "Un meilleur cadeau commence par une meilleure planification.",
    resourcesText: "Préparez audience, volume, destinations et délais avant le premier échange.",
    nextStep: "Étape suivante",
    caseStudies: "Études de cas",
    brandTagline: "Conciergerie cadeaux d’entreprise",
  },
  de: {
    home: "Start",
    startProject: "Projekt starten",
    exploreServices: "Leistungen ansehen",
    turnkeyProcess: "Schlüsselfertiger Prozess",
    occasions: "Anlässe und saisonale Programme",
    whoWeServe: "Für wen wir arbeiten",
    startingPoints: "Flexible Einstiege",
    relatedServices: "Verwandte Leistungen",
    relatedTitle: "Kombinieren Sie Leistungen nach Projektform.",
    relatedText: "Corporate Gifting, Boxen, Concierge und Fulfillment können zusammen oder einzeln genutzt werden.",
    howWorkComes: "So fügt sich die Arbeit zusammen",
    industriesTeams: "Branchen und Teams",
    cmsReady: "CMS-bereit",
    cmsTitle: "Weitere Branchenseiten sind im Inhaltsmodell vorgesehen.",
    cmsText: "Die Website kann Branchenseiten ergänzen, ohne die öffentliche Struktur zu ändern.",
    fromIdea: "Von der Idee bis zur Tür",
    insights: "Impulse",
    insightsTitle: "Nützliche Gedanken für besseres Corporate Gifting.",
    insightsText: "Notizen zu VIP-Programmen, Saisonkampagnen, Markenboxen und Logistik.",
    challenge: "Herausforderung",
    approach: "Möglicher Ansatz",
    outcome: "Angestrebtes Ergebnis",
    openResource: "Offene Ressource",
    resourceNote: "Dies ist eine Planungshilfe, keine Preisliste. Jedes Projekt wird nach Umfang kalkuliert.",
    services: "Leistungen",
    servicesTitle: "Leistungen, die zu einem Projekt werden können.",
    servicesText: "Nutzen Sie eine Leistung oder kombinieren Sie sie zu einem vollständig betreuten Programm.",
    explore: "Entdecken",
    testimonials: "Stimmen",
    testimonialsTitle: "Der Sinn der bestehenden Stimmen bleibt erhalten.",
    testimonialsText: "Kundennoten zu Lager, Fulfillment, Koordination und Sorgfalt — klarer formuliert.",
    gallery: "Galerie",
    galleryTitle: "Visueller Kontext für Geschenke, Verpackung und Fulfillment.",
    galleryText: "Die aktuellen Bilder sind Platzhalter, bis Premiumfotografie vorliegt.",
    viewGallery: "Galerie ansehen",
    resources: "Ressourcen",
    resourcesTitle: "Besseres Schenken beginnt mit besserer Planung.",
    resourcesText: "Bereiten Sie Zielgruppe, Umfang, Ziele und Zeitplan vor dem ersten Gespräch vor.",
    nextStep: "Nächster Schritt",
    caseStudies: "Fallstudien",
    brandTagline: "Concierge für Corporate Gifting",
  },
  pt: {
    home: "Início",
    startProject: "Começar um projeto",
    exploreServices: "Ver serviços",
    turnkeyProcess: "Processo chave na mão",
    occasions: "Ocasiões e programas sazonais",
    whoWeServe: "A quem servimos",
    startingPoints: "Pontos de partida flexíveis",
    relatedServices: "Serviços relacionados",
    relatedTitle: "Combine serviços conforme a forma do projeto.",
    relatedText: "Gifting corporativo, caixas, concierge e fulfillment podem ser usados juntos ou em separado.",
    howWorkComes: "Como o trabalho se junta",
    industriesTeams: "Setores e equipas",
    cmsReady: "Pronto para CMS",
    cmsTitle: "Páginas de setores futuras já cabem no modelo de conteúdo.",
    cmsText: "O site pode crescer páginas de indústria sem mudar a estrutura pública.",
    fromIdea: "Da ideia até à porta",
    insights: "Artigos",
    insightsTitle: "Ideias úteis para um melhor gifting corporativo.",
    insightsText: "Notas sobre programas VIP, campanhas sazonais, caixas de marca e logística.",
    challenge: "Desafio",
    approach: "Abordagem possível",
    outcome: "Resultado pretendido",
    openResource: "Recurso aberto",
    resourceNote: "Isto é um guia de planeamento, não uma lista de preços. Cada projeto é orçamentado por âmbito.",
    services: "Serviços",
    servicesTitle: "Serviços que podem formar um só projeto.",
    servicesText: "Use um serviço ou combine-os num programa totalmente gerido.",
    explore: "Explorar",
    testimonials: "Testemunhos",
    testimonialsTitle: "O sentido dos testemunhos atuais é preservado.",
    testimonialsText: "Notas de clientes sobre armazenamento, fulfillment, coordenação e cuidado — reescritas com clareza.",
    gallery: "Galeria",
    galleryTitle: "Contexto visual para presentes, embalagem e fulfillment.",
    galleryText: "As imagens atuais são referência até haver fotografia premium.",
    viewGallery: "Ver galeria",
    resources: "Recursos",
    resourcesTitle: "Um melhor presente começa com um melhor planeamento.",
    resourcesText: "Prepare audiência, escala, destinos e prazos antes da primeira conversa.",
    nextStep: "Próximo passo",
    caseStudies: "Casos",
    brandTagline: "Concierge de gifting corporativo",
  },
  zh: {
    home: "首页",
    startProject: "开始项目",
    exploreServices: "了解服务",
    turnkeyProcess: "一站式流程",
    occasions: "场合与季节性项目",
    whoWeServe: "服务对象",
    startingPoints: "灵活起点",
    relatedServices: "相关服务",
    relatedTitle: "按项目形态组合服务。",
    relatedText: "企业礼赠、定制礼盒、礼宾与履约可单独使用，也可组合。",
    howWorkComes: "工作如何衔接",
    industriesTeams: "行业与团队",
    cmsReady: "已适配 CMS",
    cmsTitle: "内容模型已预留更多行业页。",
    cmsText: "站点可以增加行业页，而无需改动公开信息结构。",
    fromIdea: "从想法到送达",
    insights: "洞察",
    insightsTitle: "把企业礼赠做得更好的实用思考。",
    insightsText: "关于 VIP 计划、季节活动、品牌礼盒与履约的笔记。",
    challenge: "挑战",
    approach: "可行做法",
    outcome: "预期结果",
    openResource: "公开资源",
    resourceNote: "这是规划指南，不是价目表。每个项目都按范围报价。",
    services: "服务",
    servicesTitle: "可以组合成一个项目的服务。",
    servicesText: "使用单项服务，或组合成全程托管的礼赠计划。",
    explore: "了解更多",
    testimonials: "客户评价",
    testimonialsTitle: "保留现有评价的原意。",
    testimonialsText: "客户关于仓储、履约、协调与细致服务的反馈，已重新写得更清晰。",
    gallery: "图库",
    galleryTitle: "礼赠、包装与履约的视觉参考。",
    galleryText: "在获得更高品质摄影前，先使用现有图片作为占位。",
    viewGallery: "查看图库",
    resources: "资源",
    resourcesTitle: "更好的礼赠，始于更好的规划。",
    resourcesText: "在第一次沟通前，先准备好受众、规模、目的地与时间。",
    nextStep: "下一步",
    caseStudies: "案例",
    brandTagline: "企业礼赠礼宾服务",
  },
  ar: {
    home: "الرئيسية",
    startProject: "ابدأ مشروعاً",
    exploreServices: "استكشف الخدمات",
    turnkeyProcess: "عملية متكاملة",
    occasions: "المناسبات والبرامج الموسمية",
    whoWeServe: "من نخدم",
    startingPoints: "نقاط انطلاق مرنة",
    relatedServices: "خدمات ذات صلة",
    relatedTitle: "اجمع الخدمات حسب شكل المشروع.",
    relatedText: "يمكن استخدام الهدايا المؤسسية والصناديق المخصصة والكونسيرج والتنفيذ معاً أو كلٌّ على حدة.",
    howWorkComes: "كيف يكتمل العمل",
    industriesTeams: "القطاعات والفرق",
    cmsReady: "جاهز لنظام المحتوى",
    cmsTitle: "صفحات القطاعات المستقبلية جاهزة في نموذج المحتوى.",
    cmsText: "يمكن للموقع إضافة صفحات قطاعات دون تغيير بنية المعلومات العامة.",
    fromIdea: "من الفكرة إلى الباب",
    insights: "مقالات",
    insightsTitle: "أفكار مفيدة لهدايا شركات أفضل.",
    insightsText: "ملاحظات حول برامج VIP والحملات الموسمية والصناديق ذات العلامة واللوجستيات.",
    challenge: "التحدي",
    approach: "نهج محتمل",
    outcome: "النتيجة المقصودة",
    openResource: "مورد مفتوح",
    resourceNote: "هذا دليل تخطيط وليس قائمة أسعار. يُسعَّر كل مشروع حسب النطاق.",
    services: "الخدمات",
    servicesTitle: "خدمات يمكن أن تعمل كمشروع واحد.",
    servicesText: "استخدم خدمة واحدة أو اجمعها في برنامج هدايا يُدار بالكامل.",
    explore: "استكشف",
    testimonials: "آراء العملاء",
    testimonialsTitle: "تم الحفاظ على معنى التقييمات الحالية.",
    testimonialsText: "ملاحظات العملاء حول التخزين والتنفيذ والتنسيق والعناية — أُعيدت صياغتها بوضوح.",
    gallery: "المعرض",
    galleryTitle: "سياق بصري للهدايا والتغليف والتنفيذ.",
    galleryText: "الصور الحالية مؤقتة إلى حين توفير تصوير فاخر.",
    viewGallery: "عرض المعرض",
    resources: "موارد",
    resourcesTitle: "هدية أفضل تبدأ بتخطيط أفضل.",
    resourcesText: "جهّز الجمهور والحجم والوجهات والجدول قبل أول محادثة.",
    nextStep: "الخطوة التالية",
    caseStudies: "دراسات الحالة",
    brandTagline: "كونسيرج الهدايا المؤسسية",
  },
  he: {
    home: "בית",
    startProject: "דברו איתנו",
    exploreServices: "לשירותים",
    turnkeyProcess: "תהליך עבודה מלא",
    occasions: "אירועים ועונות שמתאימים למתנות",
    whoWeServe: "למי זה מתאים",
    startingPoints: "רעיונות טובים להתחלה",
    relatedServices: "שירותים קשורים",
    relatedTitle: "אפשר לשלב שירותים לפי הצורך.",
    relatedText: "כל פרויקט מתוכנן לפי קהל, היקף, מיתוג, יעדים ולוח זמנים.",
    howWorkComes: "תהליך העבודה",
    industriesTeams: "צוותים ותחומים",
    cmsReady: "תוכן עתידי",
    cmsTitle: "עמודי תחומים נוספים מוכנים להמשך.",
    cmsText: "עמוד הגיימינג מפורסם עכשיו. שאר התחומים שמורים לכתיבה ממוקדת יותר לפני פרסום.",
    fromIdea: "מהרעיון ועד ההגעה ליעד",
    insights: "מאמרים",
    insightsTitle: "תובנות שימושיות על מתנות ארגוניות.",
    insightsText: "מאמרים קצרים על אסטרטגיה, VIP, חגים, קופסאות ממותגות ולוגיסטיקה.",
    challenge: "האתגר",
    approach: "הגישה",
    outcome: "התוצאה",
    openResource: "מדריך פתוח",
    resourceNote: "המדריך פתוח כרגע ואינו דורש הרשמה לניוזלטר. בהמשך אפשר להפוך אותו להורדה עם הרשמה.",
    services: "שירותים",
    servicesTitle: "שירותים שאפשר לשלב בפרויקט אחד.",
    servicesText: "ההתמקדות היא מתנות ארגוניות, קופסאות ממותגות, קונסיירז' ולוגיסטיקה.",
    explore: "למידע נוסף",
    testimonials: "המלצות",
    testimonialsTitle: "מה לקוחות מעריכים בעבודה איתנו.",
    testimonialsText: "תיאום מסודר, רעיונות טובים וביצוע שאפשר לסמוך עליו.",
    gallery: "גלריה",
    galleryTitle: "השראה חזותית למתנות, אריזות ושילוח.",
    galleryText: "התמונות זמניות עד להחלפה בתמונות פרימיום חדשות.",
    viewGallery: "לגלריה",
    resources: "משאבים",
    resourcesTitle: "תכנון מתנות מתחיל בהחלטות טובות.",
    resourcesText: "שלושה מדריכים פתוחים מוכנים לשימוש, עם מבנה שמתאים להמרה ל-PDF בעתיד.",
    nextStep: "השלב הבא",
    caseStudies: "פרופילי פרויקטים",
    brandTagline: "קונסיירז' למתנות ארגוניות",
  },
};
